Added excel writer output
ulido/pzfx_parser pull request #1
Opened 2021-02-26 04:09 UTC by Dolzen

Hi I fixed an issue where the reader would fail if a column was empty.

I also made a new function which will convert the prism file into xlsx, I made this because I don't have a prism lisence and couldn't copy the data out of prism I got from someone else.

Hopefully this helps someone else :D

2021-03-03 09:58 UTC, ulido requested changes
Hi! Thank you very much for fixing the empty column issue and implementing the excel writer. I am happy to merge this - but please see my comments below.

2021-03-03 09:58 UTC, ulido commented on pzfx_parser.py
> +    return
Please add a newline at the end of the file - sorry to be nitpicky.

2021-03-03 09:58 UTC, ulido commented on pzfx_parser.py
> +def convert_pzfx_to_excel(filename,output):
Thanks for implementing this! However, I think it would be more useful if it could take a `tables` dictionary (i.e. the output of `read_pzfx` instead of a filename. This way, the user has an opportunity to make modifications to the tables before they are saved. This would allow this to be more of a utility function than an encapsulation. The user can then write `convert_pzfx_to_excel(read_pzfx(filename), output)`.

Instead of calling the output filename argument `output`, can you please rename it to `output_filename`? This makes it clear what type of input is needed. In python it is quite common for IO functions to take an open file descriptor instead, which makes `output` a bit ambiguous.

I.e. something like this:
```suggestion
def convert_pzfx_to_excel(tables, output_filename):
    """Takes a `tables` dict (from `read_pzfx`) and writes to an xlsx file, returns nothing."""
    with pd.ExcelWriter(output_filename, engine='openpyxl') as writer:
        for df_name, df in tables.items():
            for c in '\/*[]:?':
                df_name = df_name.replace(c, '')
            df.to_excel(writer, sheet_name=df_name)
    return
```

2021-03-03 10:05 UTC, Dolzen commented
Sounds good I'll make the changes soon, pretty new to PR and github collaboration so thank you for your comments.

:)

2021-03-03 11:43 UTC, ulido commented
Great, thank you! Same here, first PR I got. :-)

2021-03-04 00:21 UTC, Dolzen commented
Ok I've added the changes so now the xslx write function takes a pandas dictionary and writes it to xlsx (dropping unsupported characters in the column names). I accepted the changes you've made and they should now appear in the pull request. It could be changed to write as a csv but xlslx supports the sheets format better in my opinion.

Let me know if any issues. I hope these functions will be useful to other researchers. The Pzfx format is quite frustrating to use without a license, it isn't even possible to copy data embedded in a pxfx file using the demo version of PRISM. Now those who don't have a licesnse can at least access their data.

2021-03-04 09:14 UTC, ulido approved these changes
Thank you very much! I've approved it, and I'll push a new version to PyPI.

Yes, I agree with you on the frustration with the pzfx files and needing a license to even get the data out. This is why I started this little python module.

2021-03-04 09:15 UTC, merged